---
title: '**STOR 566: Intro to Deep Learning**'
geometry: margin=2
output:
  prettydoc::html_pretty:
    theme: architect
  html_document:
    toc: yes
    df_print: paged
  pdf_document:
    toc: yes
---

<style type="text/css">

div {
color: #13294B;
}

#TOC {
  color: #4B9CD3;
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
  color: #4B9CD3;
  background-color: #13294B;
}

a:link {
    color: #4B9CD3;
    text-decoration: none;
}

a:visited {
        text-decoration: none;
color: #4B9CD3;

}
a:hover {
color: #4B9CD3;
background-color: #13294B;
}

.main-container {
  max-width: 300px;
  margin-left: auto;
  margin-right: auto;
}

.column {
  float: left;
  width: 50%;
}

.row:after {
  content: "";
  display: table;
  clear: both;
} 

</style>

# **About the Course**

See the **[syllabus](Syllabi/566_Syllabus.pdf)** for details. Deep neural networks (DNNs) have been widely used for tackling numerous machine learning problems that were once believed to be challenging. With their remarkable ability of fitting training data, DNNs have achieved revolutionary successes in many fields such as computer vision, natural language progressing, and robotics. This is an introduction course to deep learning. Topics covered by this course include but are not limited to:

1. Machine Learning Overview
2. Optimization
3. MLP, CNN, RNN, GNN
4. Generative models
5. Advanced topics

- Instructor: **[Yao Li](https://liyao880.github.io/yaoli/)**

- Teaching Assistant: **[Kyung Rok Kim](https://stor.unc.edu/people/graduate-students/)**

- Grader: **Chengze Xie**
    
- Class: TTH 3:30PM-4:45PM, Hanes 120
    
- Office Hours:
    - Instructor Office Hours: W 4:00PM-5:00PM, Hanes 334
    - TA Office Hours: M 10:00AM-12:00PM, [Zoom](https://unc.zoom.us/j/94946966524)


# **Course Material**

| Date | Lecture | Slides | Tutorial|
|------|-----------------------|-------:|----------:|
|Aug. 20| Welcome |[Slides](Lecture/Lecture_01_Course_Overview.pdf)| |
|Aug. 22| Overview of Machine Learning |[Slides](Lecture/Lecture_02_Overview_of_Machine_Learning.pdf)| [Colab](https://drive.google.com/file/d/1ky_ypXVHpql89OSIMu1M8PF2VRSojVrg/view?usp=sharing)|
|Aug. 27| Linear Regression and Classification |[Slides](Lecture/Lecture_03_Linear_Regression.pdf)| |
|Aug. 29| Optimization |[Slides](Lecture/Lecture_04_Optimization.pdf)| |
|Sep. 03| Well-Being Day || |
|Sep. 05| Kernel Methods |[Slides](Lecture/Lecture_05_Kernel_Methods.pdf)| |
|Sep. 10| Neural Networks |[Slides](Lecture/Lecture_06_Neural_Networks.pdf)| |
|Sep. 12| Convolutional Neural Networks I |[Slides](Lecture/Lecture_07_CNN_I.pdf)| |
|Sep. 17| Convolutional Neural Networks II |[Slides](Lecture/Lecture_08_CNN_II.pdf)| HW1 Review|
|Sep. 19|Convolutional Neural Networks III|[Tutorial 1](https://colab.research.google.com/drive/12OTyDqb3mWqOjYzvzlo_p7KWfBTdA-3x?usp=sharing)|[ResNet](Presentation/DeepResidualLearning.pdf)|
|Sep. 24| Recurrent Neural Networks|[Slides](Lecture/Lecture_09_RNN.pdf)| |
|Sep. 26| GRU and LSTM |[Slides](Lecture/Lecture_10_LSTM_and_GRU.pdf)| |
|Oct. 01| Project Proposal Discussion || |
|Oct. 03| Project Proposal Discussion || |
|Oct. 08| NLP Pre-training |[Slides](Lecture/Lecture_11_NLP_Pre_training.pdf)| [Word2Vec](Presentation/Word2Vec.pdf)|
|Oct. 10| Generative Models |[Slides](Lecture/Lecture_12_Generative_Models_I.pdf)|[GAN](Presentation/GAN.pdf) |
|Oct. 15| Online Tutorial |[Zoom](https://unc.zoom.us/j/94946966524)| [Tutorial 2](https://colab.research.google.com/drive/1xS1UwjrI8-hkz4dLrbCIukGxaKclCkWv?usp=sharing)|
|Oct. 17| Fall Break || |
|Oct. 22| Adversarial Attack|[Slides](Lecture/Lecture_14_Adversarial_Attack.pdf)| |
|Oct. 24| Networks Opinions (Guest Presentation) |[Slides](Lecture/Networks_Opinions.pdf)| |
|Oct. 29| Adversarial Defense |[Slides](Lecture/Lecture_15_Adversarial_Defense.pdf)| |
|Oct. 31| Transformer |[Slides](Lecture/Lecture_16_Transformer.pdf)|[BERT](Presentation/BERT.pdf) |
|Nov. 05| Vision Transformer |[Slides](Lecture/Lecture_17_Transformers_for_Vision.pdf)| HW3 Review |
|Nov. 07| Federated Learning |[Slides](Lecture/Lecture_18_Federated_Learning.pdf)| pFL|
|Nov. 12| Poisoning Attack |[Slides](Lecture/Lecture_19_Poisoning_and_Backdoor_Attack.pdf)| |
|Nov. 14| Poisoning Defense |[Slides](Lecture/Lecture_20_Backdoor_Defense.pdf)| HW4&5 Review|
|Nov. 19| Large Language Models |[Slides](Lecture/LLM.pdf)||
|Nov. 21| Final Project Work Day || |
|Nov. 26| Final Presentation || |
|Nov. 28| Thanksgiving || |
|Dec. 03| Final Presentation || |


# **Homework Tracker**

All homework assignments are to be submitted via **[Canvas](https://edtech.unc.edu/service/canvas/)**. Late homework will receive a grade of **0**.

| Date assigned | Instructions | Due Date (Time) |
|----------|:--------:|:-------------:|
| Aug. 29  | [HW1](https://drive.google.com/drive/folders/1eLEDBbeqPZwN5PViA49rw7y80LoPqEww?usp=sharing)([.ipynb](https://colab.research.google.com/drive/1JctgZulBiKP0aft19oNopkSJF9KR84J2?usp=sharing)) |  Sep. 15 (11:59 PM) |
| Sep. 12  | [HW2](https://drive.google.com/drive/folders/1SG9W7V2i4yhSzWupKapFwV5qm7KeKVef?usp=sharing)([.ipynb](https://colab.research.google.com/drive/1d-t3fDdkvdC3s5HUV4qn3O-gQ3mH7DwC?usp=sharing)) |  Oct. 02 (11:59 PM) |
| Oct. 01  | [HW3](https://drive.google.com/drive/folders/10rEevuA6iatidLyKLy9-rggI6PasI0wW?usp=sharing)([.ipynb](https://colab.research.google.com/drive/137JacA8aCc0-SmhfZrJ9UgoEQI8EgDY6?usp=sharing)) |  Oct. 13 (11:59 PM) |
| Oct. 13  | [HW4](https://drive.google.com/drive/folders/1qgJzqdm_TLh6KgKovG_9sxT5qLsJQ-jU?usp=sharing)([.ipynb](https://colab.research.google.com/drive/1M4ixWZtzj6mUkKm6U8fH0jICBHk2OClt?usp=sharing)) |  Oct. 30 (11:59 PM) |
| Oct. 29  | [HW5](https://drive.google.com/drive/folders/1grxJzdFhhdpc-SFQIKkhqRTVSwktJMSF?usp=sharing)([.ipynb](https://colab.research.google.com/drive/1oXiE4r4lyTTJoJn_BPbI4YfeVbOTbhar?usp=sharing))  |  Nov. 10 (11:59 PM) |
|          |        |           |

# **Final Project Details**

This course includes a final project in lieu of a final exam. Projects will be completed in groups of **four** and consist of:

- Project Proposal (10%)
- Project Presentation (30%)
- Project Paper (50%)
- Peer Review Score (10%)

## Group List

Please form the final project group before **August 30th**, and sign up using the shared **[spreadsheet](https://docs.google.com/spreadsheets/d/1tbKkaZUSgc5aJsr4jqzF2ylP9AOmOGH2t2P95ZOgPp8/edit?usp=sharing)**. Please don't modify the information of other groups.

## Four Parts Including Point Values

I will meet with each group to discuss the final project topic. Project topics can be:

- Solve an interesting or new problem with existing method
- Develop a new algorithm/model
- Compare state-of-the-art algorithms on some problems
- ...

**P1: Project Proposal** *(10 Points):* The project proposal is limited to 2-page (excluding reference) and contains:

- Problem to solve
- Review of existing studies in this field
- Your proposed method or Methods you would like to compare
- Evaluation metric
- Reference

See latex template at [link](https://drive.google.com/file/d/16uQ-fbVysshhh13xvnpNy5GYPAMcplDK/view?usp=sharing).

**P2: Project Presentation** *(30 Points):* All groups will present their final projects during the last week or two weeks of classes. Every group member is expected to join the presentation. The length of the presentation depends on the number of groups (10–20min) and will be announced later.

You can find the presentation slides of all the groups at [here](https://drive.google.com/drive/folders/1ExvGJwXaQfOHYrbFjsU79BnPKvq5rUJm?usp=sharing).

**P3: Project Paper** *(50 Points):* Each team must submit a written project report. It is recommended to include a discussion of how your research work can be further extended. It is required to use the [NeurIPS Latex style files](https://neurips.cc/Conferences/2022/PaperInformation/StyleFiles) and submit the report in PDF format. The report should be less than 8 pages without references (no minimum requirement).

**P4: Peer Score** *(10 Points):* Ten points of the final project is based on an average score measuring overall contribution as seen by you and the other members of your group. Each group member should score every person in their group on a continuous scale from 0 (Bad) to 10 (Good). Before the due date of the final paper, every member is required to submit the group scoring through the google survey link below. Your name and this information will remain private between me and you. If you fail to submit this group scoring before the deadline, 2 points penalty will be applied and I will give the other members a score of 10.

- [Peer Scoring](https://forms.gle/iDHQDysHiz96khPh7)

    
## Due Dates of Individual Parts

| Part | Description |Method (Location) of Submission| Due Date (Time) |
|------|-------------|-------------|---------------------:|
| P1  | Project Proposal | Canvas | Sep. 29 (11:59PM)|
|   | Proposal Meeting | Hanes 334 | Oct. 01 / Oct. 03 (3:30PM-4:45PM)|
| P2  | Presentation Slides |Canvas| Nov. 20 / Nov. 25 (11:59PM)|
|   | Final Presentation|Class| Nov. 21 / Nov. 26 (3:30PM-4:45PM)|
| P3  | Final Report|Canvas|Dec. 04 (11:59PM)|
| P4  | Peer Scoring|[Google Survey](https://forms.gle/iDHQDysHiz96khPh7)|Dec. 04 (11:59PM)|

# **Paper Presentation**

Check the **[paper list](https://docs.google.com/spreadsheets/d/1K4QImxxBO14hBnjr65Ex5a2nz3Fy2mFExfIBKEOlVTY/edit?usp=sharing)** for paper presentation opportunity.

# **Reading**

- **[Deep Learning](https://www.deeplearningbook.org/)**, by Ian Goodfellow, Yoshua Bengio, Aaron Courville. 
- **[Deep learning theory lecture note](https://mjt.cs.illinois.edu/dlt/)**, by Matus Telgarsky.
- **[Foundations of machine learning](https://cs.nyu.edu/~mohri/mlbook/)**, by Mehryar Mohri, Afshin Rostamizadeh, and Ameet Talwalkar.
- **[Convex optimization](https://stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf)**, by Stephen Boyd, and Lieven Vandenberghe.

This page was last updated on `r Sys.time()` Eastern Time.
